[build]
  # BYPASS TOTAL - NÃO EXECUTAR NADA
  command = "echo 'Deploy estático - sem build necessário'"
  publish = "."
  ignore = "exit 0"

[build.environment]
  # FORÇA DESABILITAÇÃO COMPLETA
  SKIP_INSTALL = "true"
  DISABLE_YARN = "true"
  DISABLE_NPM = "true"
  NODE_ENV = "production"
  CI = "false"
  NETLIFY_SKIP_YARN_INSTALL = "true"
  NETLIFY_SKIP_NPM_INSTALL = "true"

[[headers]]
  for = "/*"
  [headers.values]
    # CACHE BUSTING EXTREMO
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Content-Type = "text/html; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# CONFIGURAÇÃO ESPECIAL PARA EVITAR DETECÇÃO DE FRAMEWORKS
[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = false 