[build]
  publish = "."
  command = ""
  ignore = "exit 0"

[build.environment]
  SKIP_INSTALL = "true"
  DISABLE_YARN = "true"
  DISABLE_NPM = "true"

[[redirects]]
  from = "/*"
  to = "/simple.html"
  status = 200
  
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[redirects]]
  from = "/old-system"
  to = "/"
  status = 301
  force = true 