[build]
  # CONFIGURAÇÃO PARA BYPASS COMPLETO DE DEPENDÊNCIAS
  command = ""
  publish = "."
  ignore = "exit 0"

[build.environment]
  # FORÇA BYPASS DE INSTALAÇÃO
  SKIP_INSTALL = "true"
  DISABLE_YARN = "true"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    # CACHE BUSTING EXTREMO
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"
    Content-Type = "text/html; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/old-system"
  to = "/"
  status = 301
  force = true 